name: menu
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: 
  cloud_firestore: 
  firebase_auth: 
  provider: ^6.0.4
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
  - assets/imagen.png
  - assets/menu.png
  - assets/pastas.png
  - assets/sedes.png
  - assets/factural.png
  - assets/logoPicadas.png
  - assets/lomejor.png
  - assets/loguito.png
  - assets/login.png
  - assets/tradicionales.png
  - assets/arma.png
  - assets/sedesi.png
  - assets/sugerencias.png
  - assets/registro.png
  - assets/Ubicacion 3.png
  - assets/Ubicacion 2.png
  - assets/Ubicacion 1.png
  - assets/tradicionv.png
  - assets/armapicada.png
  - assets/carrito.png
  - assets/sugerencia.png
  fonts:
  - family: Gagaline
    fonts:
      - asset: fonts/Gagalin-Regular.otf


  

  

  
